import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import SessionControl from "@/components/SessionControl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<SessionControl>{children}</SessionControl>
				</AuthProvider>
			</body>
		</html>
	);
}
